---
title: "Herbarium App Set up"
author: "Kristen Peach"
date: "2/20/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

1. Load Packages

```{r}

library(tidyverse)
library(sf)
library(tmap)
library(leaflet)

```

```{r}

#Load Subset of data
library(readr)
CCH_subset <- read_csv("CCH_subset.csv")


```


```{r}

library(leaflet)

m <- leaflet() %>%
  addTiles() %>%  # Add default OpenStreetMap map tiles
  addMarkers(lng=174.768, lat=-36.852,
    popup="The birthplace of R")
m  # Print the map



```


```{r}


leaflet() %>% addCircles(data = CCH_subset)
leaflet() %>% addCircles(data = CCH_subset, lat = ~ Latitude, lng = ~ Longitude) %>% 
addTiles()
   





```




```{r}

Aster_map <- filter(CCH_subset, family == "Asteraceae") %>% 
  select(family, Latitude, Longitude)



```

```{r}

## create a list of countries
Aster_fam <- CCH_subset %>% ## use instead of gapminder
  filter(family == "Asteraceae")

family_list <- unique(CCH_subset$family) 
family_list


```


Filtering the CCH_subset data to return a plot counts of showing species
```{r}


#This creates a df of the top ten frequency
CCH_subset_plot <- CCH_subset %>% filter(family == "Asteraceae") %>% count(species) %>% arrange(n) %>% tail(10)

ggplot(CCH_subset_plot, aes(x = species, y = n)) + 
  geom_col() +
  xlab = "Top 10 Species Collected" +
  ylab = "Frequency of Collection"

```








